version: '3.7'

name: lafs-api-stack

services:
  lafs-api:
    container_name: lafs-api
    image: lafs-api:latest
    restart: always
    build: .
    environment:
      DB_HOST: "lafs-db"
      DB_PORT: 27017
      DB_USER: ""
      DB_PASSWORD: ""
      DB_NAME: "lafs"
      DB_URL: "mongodb://lafs-db:27017/lafs"
    ports:
      - 3000:3000
    links:
      - lafs-db
  lafs-db:
    container_name: lafs-db
    image: mongo:4
    ports:
      - 27017:27017

networks:
  default:
    external:
      name: lafs-net
